import Link from "next/link";
import LiveDate from "../components/LiveDate";
import RecruiterShell from "../components/RecruiterShell";

export default function Overview() {
  return (
    <RecruiterShell>
      <header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4 sm:px-8">
        <div><LiveDate /><h1 className="mt-1 text-xl font-semibold tracking-tight text-slate-900">Good morning, Adil</h1></div>
        <div className="flex items-center gap-3"><button className="hidden rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 sm:block">View as candidate</button><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#dcefeb] text-sm font-bold text-[#1f6f68]">AR</div></div>
      </header>
      <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
        <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-[#1f6f68]">Workspace overview</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-slate-900">Your hiring pipeline</h2><p className="mt-2 text-sm text-slate-500">Review interview progress and discover your strongest candidates.</p></div><Link href="/jobs/new" className="rounded-lg bg-[#1f6f68] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-[#185b55]">Create a job</Link></section>
        <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Workspace metrics"><MetricCard label="Active jobs" value="06" change="+2 this month" /><MetricCard label="Candidates screened" value="128" change="+18% from last month" /><MetricCard label="Completion rate" value="84.6%" change="+6.2% from last month" /><MetricCard label="Minutes remaining" value="613" change="of 1,000 plan minutes" /></section>
        <section className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_1fr]">
          <div className="rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 className="font-semibold text-slate-900">Active jobs</h3><p className="mt-1 text-xs text-slate-500">Track candidates across your open roles.</p></div><Link href="/jobs" className="text-sm font-semibold text-[#1f6f68] hover:underline">View all</Link></div><div className="divide-y divide-slate-100"><JobRow title="Senior Backend Engineer" candidates="32 candidates" progress="78%" tone="teal" /><JobRow title="Product Designer" candidates="18 candidates" progress="54%" tone="blue" /><JobRow title="Junior Python Developer" candidates="41 candidates" progress="36%" tone="amber" /></div></div>
          <div className="rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h3 className="font-semibold text-slate-900">Recent interviews</h3><p className="mt-1 text-xs text-slate-500">Reports ready for your review.</p></div><div className="divide-y divide-slate-100"><InterviewRow initials="HM" name="Hassan Malik" role="Backend Engineer" score="86" /><InterviewRow initials="SA" name="Sara Ahmed" role="Product Designer" score="79" /><InterviewRow initials="OK" name="Omar Khan" role="Python Developer" score="74" /></div><div className="px-5 py-4"><Link href="/reports" className="block w-full rounded-lg border border-slate-200 py-2 text-center text-sm font-semibold text-slate-600 hover:bg-slate-50">Open reports</Link></div></div>
        </section>
        <section className="mt-6 rounded-2xl border border-[#cde4df] bg-[#eef7f5] p-5 sm:flex sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-[#1f6f68]">Ready to create your next interview?</p><p className="mt-1 text-sm text-slate-600">Define a job rubric first, then let Screenwise handle the first round.</p></div><Link href="/jobs/new" className="mt-4 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-[#1f6f68] shadow-sm ring-1 ring-inset ring-[#cde4df] hover:bg-[#f9fffd] sm:mt-0">Start with a job</Link></section>
      </div>
    </RecruiterShell>
  );
}

function MetricCard({ label, value, change }: { label: string; value: string; change: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-slate-900">{value}</p><p className="mt-2 text-xs font-medium text-[#1f6f68]">{change}</p></div>; }
function JobRow({ title, candidates, progress, tone }: { title: string; candidates: string; progress: string; tone: "teal" | "blue" | "amber" }) { const colors = { teal: "bg-[#1f6f68]", blue: "bg-blue-500", amber: "bg-amber-500" }; return <div className="px-5 py-4"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-slate-800">{title}</p><p className="mt-1 text-xs text-slate-500">{candidates}</p></div><span className="text-sm font-semibold text-slate-700">{progress}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${colors[tone]}`} style={{ width: progress }} /></div></div>; }
function InterviewRow({ initials, name, role, score }: { initials: string; name: string; role: string; score: string }) { return <div className="flex items-center gap-3 px-5 py-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-slate-600">{initials}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-800">{name}</p><p className="mt-1 truncate text-xs text-slate-500">{role}</p></div><div className="text-right"><p className="text-sm font-bold text-[#1f6f68]">{score}/100</p><p className="mt-1 text-[11px] text-slate-400">Report ready</p></div></div>; }
